apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "agentd-secrets.fullname" . }}-config
  labels:
    {{- include "agentd-secrets.labels" . | nindent 4 }}
data:
  config.yaml: |
    services:
      {{- .Values.serviceRegistry | toYaml | nindent 6 }}
